### ISSUE TITLE
Updates to Webpage

### ISSUE THREAD

**Issue by JulieAnnKU** [zooniverse/intro-2-astro#1]
We are dropping the "Activity" portion of the lesson titles on http://zooniverse.github.io/intro-2-astro/ We want to keep everything in the same order as a way to recommend an order, but some instructors may prefer to flip around activities 2-4. Also "Introduction to People Powered Research" has been rewritten and renamed to "Galaxy Zoo 101"
- Top tabs should now read:
  Intro to Platform     HR Diagram     Galaxy Zoo 101     Hubble's Law
- Activity # should be removed from each activities page.
- Under resources "Activity 1" link should be changed to say "Introduction to the Data Analysis Platform" AND "Activity 2's HR diagram" should be changed to "the HR Diagram activity's plot"

**Comment by JulieAnnKU** [comment]
there should not be an @ before plot

**Comment by srallen** [comment]
@JulieAnnKU How should the navigation bar items be named? They're currently "Activity 1", "Activity 2", etc.

**Comment by JulieAnnKU** [comment]
The 3rd bullet point details that.

**Comment by JulieAnnKU** [comment]
the first bullet point details that

**Comment by srallen** [comment]
Done
