### ISSUE TITLE
Educator view

### ISSUE THREAD

**Issue by srallen** [zooniverse/intro-2-astro#10]
We want an educator view to see stats for the user groups they've created. See Wildcam Lab as a model.
- For each student, how many classifications completed on each project and a check-box when the assignment is completed. 
- The ability to export this list as a csv file so the instructor can export to their gradebook.

**Comment by trouille** [comment]
Does the Educator view include all the instructor's guides, etc. or do we just share that through a Google drive? I.e., the note under backlog at https://github.com/orgs/zooniverse/projects/10 about copying/sharing an Instructor's intro2astro Google drive.

**Comment by trouille** [comment]
Note: have this content behind login. Since there's isn't a student view anymore in our plans, then I don't think we need to check user role.

**Comment by trouille** [comment]
Need to find Jordan's rough wireframes or have @beckyrother start fresh.

**Comment by trouille** [comment]
https://drive.google.com/file/d/0BzeL_TYT7IYPeU9YXzY2RHpSNEk/view?usp=sharing is Jordan's rough wireframe.

**Comment by beckyrother** [comment]
@srallen @trouille is this something that's happening soon? let me know what I can do to help.

**Comment by JulieAnnKU** [comment]
Yes, Jordan and I had a conversation with Mark last Fall about these wireframes and at the time I thought it represented what Tommy and I had been talking about, but now I'm unsure how this fits in with the projects and google drive material and why the instructor's view has a classroom set up...
The classroom set up is needed within the project and to generate a folder for the instructor. I'm not sure If I'm explaining this clearly...

**Comment by srallen** [comment]
The EduAPI (what wildcam labs uses and I2A will use a modified version of it) has a data model for for 'classrooms' and 'assignments'. Essentially classrooms are Panoptes user groups that the user with the educator role can setup. Assignments are project workflows that are assigned to that group. We'll setup the available assignments that can be assigned to a group to be the workflows from the two I2A Panoptes projects. The workflows per institution on the project was only a workaround since user groups wasn't setup yet. Once those are in place (named as classrooms or whatever really), there will only be one workflow per project. 

Looking over the wireframe Jordan made, I think it will be good to ask @beckyrother to do another more refined pass on it now that we have more clear requirements.

I had suggested to Laura that the new version of the I2A site have an area that is behind login and scoped to accounts with the educator role to host the links and/or directly host files on the site that are on Google drive now. We can discuss more next week about what would be involved in trying to setup a way to clone files from a Google drive, but IMO, I think it'd be easier to directly host the files on the new site for download.

**Comment by srallen** [comment]
Closing in favor of more specific issues. Basic Educator view is done.
