### ISSUE TITLE
Groups and assignments

### ISSUE THREAD

**Issue by trouille** [zooniverse/intro-2-astro#13]
Ability for intro2astro instructor to create groups for his/her course and share a link for students to join that course's group for each assignment (as is done in wildcam).

For intro2astro, there are two projects that students will classify on:

zooniverse.org/projects/srallen/galaxy-zoo-in-astronomy-101
zooniverse.org/projects/srallen/intro2astro-hubbles-law

**Comment by trouille** [comment]
Additional notes:

For each of those projects listed above, all courses will use:

- the same subject set
- the same single workflow with the same classification task

All students enrolled in a given course will be part of the same 'group' when classifying on these projects. I.e., all 150 students in the NU fall 2017 course will be part of the same 'group'.

**Comment by srallen** [comment]
Closing in favor of zooniverse/rfc#23
