### ISSUE TITLE
Supporting instructors in copying all the Google drive materials into their own drive

### ISSUE THREAD

**Issue by trouille** [zooniverse/intro-2-astro#17]
Ability for instructors to copy a Google folder w/ all guides, handouts, etc., including all subfolders/docs, and have edit privileges. Lower priority item, since there is a solution, though clunky: https://www.youtube.com/watch?v=r_Mah5RYOnE 

Another option is for instructors to click a button to download a full .zip folder with all the Google drive materials. Then they could follow instructions for uploading that into their own Google drive. 

Note: think about how/whether to make this only accessible to instructors, vetted to be instructors in some way.

**Comment by srallen** [comment]
I think it was decided that we would not add specific functionality for this, but rather directly include content and files on the intro2astro site. (Can reopen if I misunderstood the decision on this). Feedback from students is that they do not like to go to other sites for classroom materials, so we will provide content to instructors to copy into whatever LMS the institution uses (Blackboard, etc).
