### ISSUE TITLE
ZooTools - Data Filter Helper

### ISSUE THREAD

**Issue by JulieAnnKU** [zooniverse/intro-2-astro#2]
@srallen could you change the phrasing on the check box to read "Copy all columns over to a new tab in order to compare to the whole data set." instead of "Compare filter to whole data set."

It has been very unclear to the pilot testers as to what it means.

**Comment by srallen** [comment]
Is there a date that I should plan on getting these changes done by? Thanks!

**Comment by JulieAnnKU** [comment]
We have a deadline to get material completed for Dave's class on 9/15, so maybe then would be good to make sure everything is functional before the NU quarter starts.

**Comment by srallen** [comment]
Text is updated.
