### ISSUE TITLE
Research Project added to webpage

### ISSUE THREAD

**Issue by JulieAnnKU** [zooniverse/intro-2-astro#5]
the "Research Project" needs to be added to the site

Description:
This project utilizes the skills you have developed from the in class activities to start your own research project. Included in this project is an introductory activity to guide you to begin working on the Galaxy Zoo data set. Then you will develop your own research question, use the tools to help you answer this question and create a video to communicate how you have interpreted the results. Everything you need to know is provided in the instruction below:

Instructions: https://docs.google.com/document/d/1Vecf3KhDvSL2j4TuREif0Hbb10Ym9zJTwbRhTeJFYQc/edit?usp=sharing

**Comment by srallen** [comment]
Done
