### ISSUE TITLE
Add additional activity

### ISSUE THREAD

**Issue by JulieAnnKU** [zooniverse/intro-2-astro#6]
the "Follow Up: Introduction to the Data Analysis Platform" needs to be added to the site

Description:
To introduce you to what you will be doing for your research project, you will use the tools from the in-class activity to practice asking and answering your own research question with the class data. We also introduce you to the research project data on galaxies.

Instructions: https://docs.google.com/document/d/1zhWI5cNoBW5g8NPSQmf7ftE0tpLZxmspjCNgiCpySNU/edit?usp=sharing

**Comment by srallen** [comment]
Done
