### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by trouille** [zooniverse/intro-2-astro#8]
The use case for the intro2astro project for groups is the following:

These sites will use the group functionality:
https://www.zooniverse.org/projects/srallen/intro2astro-hubbles-law
https://www.zooniverse.org/projects/srallen/galaxy-zoo-in-astronomy-101

Use cases:

For students:
When a student...

For teachers, the use case is:
When a teacher...

Is there any difference in the experience / needs for either site? For example, in https://www.zooniverse.org/projects/srallen/galaxy-zoo-in-astronomy-101/talk, the students currently post their reflection on the Nature of Science (though we could choose a different way to do this). Does this add any complexity to how groups work here?

**Comment by JulieAnnKU** [comment]
For Students:
When students need to classify on the project for the Hubble's Law activity to keep their classifications within the class so instructors can grab their results.
For the Galaxy Zoo 101 activity to be able to classify within the class to have the potential to compare their results like you can do in Galaxy Zoo Navigator.

**Comment by JulieAnnKU** [comment]
For teachers:
When instructors need to see who has participated in a project.
When instructors need to export the data for the Hubble's law activity.
When instructors may need to show the consensus results for Galaxy Zoo 101 activity.

**Comment by tjnelson5** [comment]
These look good to me.  I don't have anything to add to Julie's comments.

**Comment by trouille** [comment]
Think about how to upload videos into the Peer Review project. Is there some automated way for instructors to do this, that would link their videos to the existing peer review workflow? Or think of how to use YouTube + Google forms instead for this piece of the project.

**Comment by srallen** [comment]
Just noting here: We need to learn more about the education api and how we can leverage it for stats.

**Comment by srallen** [comment]
After discussing with @zach and @marten about Education API, it makes most sense for now to have the create and join user group functionality in the I2A web app similar to Wildcam Labs.
